CREATE TABLE AUTH(
    id  VARCHAR(10) NOT NULL,
    name VARCHAR(30) NOT NULL,
    credit VARCHAR(30) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    visit INT,
    password VARCHAR(20) NOT NULL,
    PRIMARY KEY(id)
);
ALTER TABLE AUTH ADD addr VARCHAR(50);
