CREATE TABLE ORDERS(
    order_id  INT NOT NULL AUTO_INCREMENT ,
    menu VARCHAR(10),
    style VARCHAR(10),
    customer_id VARCHAR(10) NOT NULL,
    change_list VARCHAR(255),
    PRIMARY KEY(order_id),
    FOREIGN KEY (customer_id) REFERENCES AUTH (id) ON UPDATE CASCADE
);
ALTER TABLE ORDERS ADD order_status VARCHAR(10);
ALTER TABLE ORDERS ADD numbers INT;

ALTER TABLE ORDERS ADD steak_num INT;
ALTER TABLE ORDERS ADD salad_num INT;
ALTER TABLE ORDERS ADD egg_num INT;
ALTER TABLE ORDERS ADD bacon_num INT;
ALTER TABLE ORDERS ADD bread_num INT;
ALTER TABLE ORDERS ADD total_price INT;

ALTER TABLE ORDERS DROP change_list;